"""business_category time_band_sales 컬럼 추가

Revision ID: 77f166a7d804
Revises: f3f6e9647c4a
Create Date: 2026-07-11 16:52:50.043305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77f166a7d804'
down_revision: Union[str, None] = 'f3f6e9647c4a'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_category', sa.Column('time_band_sales', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_category', 'time_band_sales')
    # ### end Alembic commands ###
