"""init seoul reb etl schema

Revision ID: 79332016126d
Revises: 
Create Date: 2026-07-07 16:28:38.125334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79332016126d'
down_revision: Union[str, None] = None
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_district',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_code', sa.String(length=50), nullable=False),
    sa.Column('district_name', sa.String(length=100), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=True),
    sa.Column('gu_name', sa.String(length=50), nullable=True),
    sa.Column('dong_name', sa.String(length=50), nullable=True),
    sa.Column('signgu_code', sa.String(length=10), nullable=True),
    sa.Column('adstrd_code', sa.String(length=10), nullable=True),
    sa.Column('avg_population', sa.Float(), nullable=True),
    sa.Column('geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # geometry 공간 인덱스는 GeoAlchemy2가 테이블 생성 시 자동 생성하므로 여기서 생성하지 않음
    op.create_index(op.f('ix_commercial_district_adstrd_code'), 'commercial_district', ['adstrd_code'], unique=False)
    op.create_index(op.f('ix_commercial_district_external_code'), 'commercial_district', ['external_code'], unique=True)
    op.create_index(op.f('ix_commercial_district_signgu_code'), 'commercial_district', ['signgu_code'], unique=False)
    op.create_table('ingestion_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('upserted_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_run_source'), 'ingestion_run', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_company', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('business_category',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commercial_district_id', sa.BigInteger(), nullable=False),
    sa.Column('district_score', sa.Float(), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('year_quarter', sa.String(length=7), nullable=False),
    sa.Column('closure_rate', sa.Float(), nullable=True),
    sa.Column('survival_rate', sa.Float(), nullable=True),
    sa.Column('open_rate', sa.Float(), nullable=True),
    sa.Column('peak_start', sa.Time(), nullable=True),
    sa.Column('peak_end', sa.Time(), nullable=True),
    sa.Column('total_business', sa.Integer(), nullable=True),
    sa.Column('tx_count', sa.Integer(), nullable=True),
    sa.Column('total_sales', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_district_id'], ['commercial_district.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commercial_district_id', 'category_name', 'year_quarter', name='uq_biz_cat_cd_name_yq')
    )
    op.create_table('foreign_population',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commercial_district_id', sa.BigInteger(), nullable=False),
    sa.Column('dimension', sa.String(length=4), nullable=False),
    sa.Column('slot', sa.String(length=10), nullable=False),
    sa.Column('foreigner_count', sa.Float(), nullable=True),
    sa.Column('total_count', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_district_id'], ['commercial_district.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commercial_district_id', 'dimension', 'slot', name='uq_foreign_pop_cd_dim_slot')
    )
    op.create_table('interest_district',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('commercial_district_id', sa.BigInteger(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_district_id'], ['commercial_district.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commercial_district_id', sa.BigInteger(), nullable=False),
    sa.Column('prediction_type', sa.String(length=20), nullable=False),
    sa.Column('target_quarter', sa.String(length=7), nullable=False),
    sa.Column('predicted_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_district_id'], ['commercial_district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('population_heatmap',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commercial_district_id', sa.BigInteger(), nullable=False),
    sa.Column('dimension', sa.Enum('time', 'day', name='heatmap_dimension_enum'), nullable=True),
    sa.Column('slot', sa.String(length=10), nullable=True),
    sa.Column('avg_population', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_district_id'], ['commercial_district.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commercial_district_id', 'dimension', 'slot', name='uq_pop_heatmap_cd_dim_slot')
    )
    op.create_table('rent_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commercial_district_id', sa.BigInteger(), nullable=False),
    sa.Column('avg_rent_per_sqm', sa.Float(), nullable=True),
    sa.Column('year_quarter', sa.String(length=7), nullable=False),
    sa.Column('floor_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_district_id'], ['commercial_district.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commercial_district_id', 'year_quarter', 'floor_type', name='uq_rent_cd_yq_floor')
    )
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('district_name', sa.String(length=100), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('report_content',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('survival_rate', sa.Float(), nullable=True),
    sa.Column('closure_rate', sa.Float(), nullable=True),
    sa.Column('open_rate', sa.Float(), nullable=True),
    sa.Column('total_business', sa.Integer(), nullable=True),
    sa.Column('peak_start', sa.Time(), nullable=True),
    sa.Column('peak_end', sa.Time(), nullable=True),
    sa.Column('district_score', sa.Float(), nullable=True),
    sa.Column('year_quarter', sa.String(length=7), nullable=True),
    sa.Column('avg_rent_per_sqm', sa.Float(), nullable=True),
    sa.Column('avg_population', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_content')
    op.drop_table('reports')
    op.drop_table('rent_stats')
    op.drop_table('population_heatmap')
    op.drop_table('ml_predictions')
    op.drop_table('interest_district')
    op.drop_table('foreign_population')
    op.drop_table('business_category')
    op.drop_table('users')
    op.drop_index(op.f('ix_ingestion_run_source'), table_name='ingestion_run')
    op.drop_table('ingestion_run')
    op.drop_index(op.f('ix_commercial_district_signgu_code'), table_name='commercial_district')
    op.drop_index(op.f('ix_commercial_district_external_code'), table_name='commercial_district')
    op.drop_index(op.f('ix_commercial_district_adstrd_code'), table_name='commercial_district')
    op.drop_table('commercial_district')
    # ### end Alembic commands ###
