"""상권별 최신분기 조회용 business_category 인덱스 추가

Revision ID: 97e030ca3096
Revises: 77f166a7d804
Create Date: 2026-07-13 15:14:54.757453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '97e030ca3096'
down_revision: Union[str, None] = '77f166a7d804'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_business_category_district_yq', 'business_category', ['commercial_district_id', 'year_quarter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_category_district_yq', table_name='business_category')
    # ### end Alembic commands ###
