"""belt/belt_member 테이블 추가

Revision ID: ab0c538fc616
Revises: 5e78cadd972b
Create Date: 2026-07-17 06:17:22.466010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ab0c538fc616'
down_revision: Union[str, None] = '5e78cadd972b'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('belt',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('anchor_gu', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_belt_slug'), 'belt', ['slug'], unique=True)
    op.create_table('belt_member',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('belt_id', sa.BigInteger(), nullable=False),
    sa.Column('commercial_district_id', sa.BigInteger(), nullable=False),
    sa.Column('is_anchor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['belt_id'], ['belt.id'], ),
    sa.ForeignKeyConstraint(['commercial_district_id'], ['commercial_district.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('belt_id', 'commercial_district_id', name='uq_belt_member')
    )
    op.create_index(op.f('ix_belt_member_belt_id'), 'belt_member', ['belt_id'], unique=False)
    op.create_index(op.f('ix_belt_member_commercial_district_id'), 'belt_member', ['commercial_district_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_belt_member_commercial_district_id'), table_name='belt_member')
    op.drop_index(op.f('ix_belt_member_belt_id'), table_name='belt_member')
    op.drop_table('belt_member')
    op.drop_index(op.f('ix_belt_slug'), table_name='belt')
    op.drop_table('belt')
    # ### end Alembic commands ###
