"""buzz_stats 테이블 추가

Revision ID: f3f6e9647c4a
Revises: d4a9c1e07b52
Create Date: 2026-07-09 05:36:43.114728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f3f6e9647c4a'
down_revision: Union[str, None] = 'd4a9c1e07b52'
branch_labels: Union[Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buzz_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commercial_district_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('buzz_index', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_district_id'], ['commercial_district.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commercial_district_id', 'source', 'period', name='uq_buzz_cd_source_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buzz_stats')
    # ### end Alembic commands ###
